POST http://localhost:3000/track HTTP/1.1
Content-Type: application/json

{
    "duration": 10,
    "referrer": "http://localhost:3000",
    "utm_source": "REST"
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 33
etag: W/"21-gPBqjJtNQPjl6lkFLhZPVda8TTc"
date: Tue, 22 Apr 2025 09:09:14 GMT
connection: close
###
GET http://localhost:3000/metrics/views?startDate=2025-03-22&endDate=2025-04-22 HTTP/1.1

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 11
etag: W/"b-qA97yBec1rrOyf2eVsYdWwFPOso"
date: Wed, 23 Apr 2025 04:20:54 GMT
connection: close
###
POST http://localhost:3000/event HTTP/1.1
Content-Type: application/json

{
    "type": "click",
    "value": "CTA_userCard"
}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 33
etag: W/"21-U3gok62QP7+K1eyQnulLkXLKYWQ"
date: Wed, 23 Apr 2025 04:42:21 GMT
connection: close