# Metrics - Get all visits
GET http://localhost:3000/metrics/views?startDate=2025-06-01&endDate=2025-06-25 HTTP/1.1
###
# get traffic sources
GET http://localhost:3000/metrics/sources?startDate=2025-06-17&endDate=2025-06-17 HTTP/1.1
# get top referrers
###
# get all events
GET http://localhost:3000/metrics/events?startDate=2025-06-02&endDate=2025-06-03 HTTP/1.1
###
# Metrics - Get average session duration
GET http://localhost:3000/metrics/sessions/average?startDate=2025-06-03&endDate=2025-06-03 HTTP/1.1